import { Influencer, Ranking, QRScan, Event, Activity, Analytics } from '@/types';

// TODO: Replace with real API calls to your backend
// This is MOCK DATA for testing the UI

// Helper function to generate random data
const randomBetween = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

// Mock Influencers Data
export const MOCK_INFLUENCERS: Influencer[] = [
  {
    id: '1',
    username: '@sarahstyle',
    fullName: 'Sarah Johnson',
    platform: 'instagram',
    profileImage: 'https://i.pravatar.cc/150?img=1',
    followers: 245000,
    following: 892,
    totalPosts: 1247,
    bio: 'Fashion & Lifestyle Creator | NYC 🗽 | Collab: sarah@email.com',
    verified: true,
    category: 'Fashion',
    location: 'New York, NY',
    email: 'sarah@email.com',
    joinedDate: '2021-03-15',
    lastActive: new Date().toISOString(),
    engagementRate: 8.5,
    averageLikes: 18500,
    averageComments: 342,
    averageShares: 89,
    reachRate: 12.3,
    overallScore: 92,
    engagementScore: 88,
    growthScore: 95,
    consistencyScore: 93,
    followerGrowth30d: 12500,
    followerGrowth7d: 3200,
    status: 'active',
    tier: 'platinum',
  },
  {
    id: '2',
    username: '@techmikereviews',
    fullName: 'Michael Chen',
    platform: 'youtube',
    profileImage: 'https://i.pravatar.cc/150?img=12',
    followers: 892000,
    following: 234,
    totalPosts: 456,
    bio: 'Tech Reviews & Tutorials | Gadget Enthusiast | Business: mike@tech.com',
    verified: true,
    category: 'Technology',
    location: 'San Francisco, CA',
    email: 'mike@tech.com',
    joinedDate: '2019-08-22',
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    engagementRate: 6.8,
    averageLikes: 45000,
    averageComments: 1200,
    averageShares: 340,
    reachRate: 15.7,
    overallScore: 95,
    engagementScore: 82,
    growthScore: 98,
    consistencyScore: 96,
    followerGrowth30d: 28000,
    followerGrowth7d: 7800,
    status: 'active',
    tier: 'platinum',
  },
  {
    id: '3',
    username: '@fitnessjenna',
    fullName: 'Jenna Martinez',
    platform: 'instagram',
    profileImage: 'https://i.pravatar.cc/150?img=5',
    followers: 567000,
    following: 445,
    totalPosts: 2134,
    bio: 'Certified Personal Trainer 💪 | Nutrition Coach | Transform your life!',
    verified: true,
    category: 'Fitness',
    location: 'Los Angeles, CA',
    email: 'jenna@fitness.com',
    joinedDate: '2020-01-10',
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    engagementRate: 9.2,
    averageLikes: 42000,
    averageComments: 890,
    averageShares: 156,
    reachRate: 14.2,
    overallScore: 89,
    engagementScore: 92,
    growthScore: 85,
    consistencyScore: 91,
    followerGrowth30d: 15600,
    followerGrowth7d: 4100,
    status: 'active',
    tier: 'gold',
  },
  {
    id: '4',
    username: '@foodie_alex',
    fullName: 'Alex Thompson',
    platform: 'tiktok',
    profileImage: 'https://i.pravatar.cc/150?img=8',
    followers: 1200000,
    following: 678,
    totalPosts: 3456,
    bio: 'Food Blogger | Recipe Creator | Trying every restaurant in NYC 🍕',
    verified: true,
    category: 'Food',
    location: 'New York, NY',
    email: 'alex@foodie.com',
    joinedDate: '2020-06-18',
    lastActive: new Date(Date.now() - 1800000).toISOString(),
    engagementRate: 11.5,
    averageLikes: 95000,
    averageComments: 2300,
    averageShares: 890,
    reachRate: 18.9,
    overallScore: 97,
    engagementScore: 96,
    growthScore: 97,
    consistencyScore: 98,
    followerGrowth30d: 45000,
    followerGrowth7d: 12000,
    status: 'active',
    tier: 'platinum',
  },
  {
    id: '5',
    username: '@travel_emma',
    fullName: 'Emma Wilson',
    platform: 'instagram',
    profileImage: 'https://i.pravatar.cc/150?img=9',
    followers: 423000,
    following: 1234,
    totalPosts: 1876,
    bio: 'Travel Photographer 📸 | 87 countries visited | Living my best life ✈️',
    verified: true,
    category: 'Travel',
    location: 'Bali, Indonesia',
    email: 'emma@travel.com',
    joinedDate: '2019-11-05',
    lastActive: new Date(Date.now() - 14400000).toISOString(),
    engagementRate: 7.8,
    averageLikes: 28000,
    averageComments: 567,
    averageShares: 234,
    reachRate: 11.5,
    overallScore: 86,
    engagementScore: 85,
    growthScore: 82,
    consistencyScore: 89,
    followerGrowth30d: 11200,
    followerGrowth7d: 2800,
    status: 'active',
    tier: 'gold',
  },
  {
    id: '6',
    username: '@gamer_david',
    fullName: 'David Rodriguez',
    platform: 'youtube',
    profileImage: 'https://i.pravatar.cc/150?img=13',
    followers: 678000,
    following: 156,
    totalPosts: 892,
    bio: 'Pro Gamer | Streamer | Esports Enthusiast | Twitch Partner',
    verified: true,
    category: 'Gaming',
    location: 'Austin, TX',
    email: 'david@gaming.com',
    joinedDate: '2018-04-12',
    lastActive: new Date(Date.now() - 900000).toISOString(),
    engagementRate: 8.9,
    averageLikes: 52000,
    averageComments: 1890,
    averageShares: 456,
    reachRate: 16.3,
    overallScore: 91,
    engagementScore: 89,
    growthScore: 90,
    consistencyScore: 94,
    followerGrowth30d: 19800,
    followerGrowth7d: 5200,
    status: 'active',
    tier: 'gold',
  },
  {
    id: '7',
    username: '@beauty_lisa',
    fullName: 'Lisa Anderson',
    platform: 'instagram',
    profileImage: 'https://i.pravatar.cc/150?img=10',
    followers: 334000,
    following: 567,
    totalPosts: 1567,
    bio: 'Makeup Artist | Beauty Tips | Skincare Routine | Cruelty-free advocate 🐰',
    verified: true,
    category: 'Beauty',
    location: 'Miami, FL',
    email: 'lisa@beauty.com',
    joinedDate: '2020-09-20',
    lastActive: new Date(Date.now() - 5400000).toISOString(),
    engagementRate: 9.7,
    averageLikes: 26000,
    averageComments: 678,
    averageShares: 123,
    reachRate: 13.1,
    overallScore: 84,
    engagementScore: 91,
    growthScore: 78,
    consistencyScore: 85,
    followerGrowth30d: 8900,
    followerGrowth7d: 2100,
    status: 'active',
    tier: 'silver',
  },
  {
    id: '8',
    username: '@business_mark',
    fullName: 'Mark Stevens',
    platform: 'twitter',
    profileImage: 'https://i.pravatar.cc/150?img=14',
    followers: 189000,
    following: 2345,
    totalPosts: 4567,
    bio: 'Entrepreneur | Business Coach | Helping you scale to 7 figures 💼',
    verified: true,
    category: 'Business',
    location: 'Chicago, IL',
    email: 'mark@business.com',
    joinedDate: '2017-02-14',
    lastActive: new Date(Date.now() - 10800000).toISOString(),
    engagementRate: 5.4,
    averageLikes: 8900,
    averageComments: 234,
    averageShares: 567,
    reachRate: 9.8,
    overallScore: 78,
    engagementScore: 72,
    growthScore: 81,
    consistencyScore: 82,
    followerGrowth30d: 5600,
    followerGrowth7d: 1400,
    status: 'active',
    tier: 'silver',
  },
  {
    id: '9',
    username: '@music_sophia',
    fullName: 'Sophia Lee',
    platform: 'tiktok',
    profileImage: 'https://i.pravatar.cc/150?img=16',
    followers: 890000,
    following: 234,
    totalPosts: 2345,
    bio: 'Singer-Songwriter 🎤 | Original Music | Covers | Spotify: Sophia Lee',
    verified: true,
    category: 'Music',
    location: 'Nashville, TN',
    email: 'sophia@music.com',
    joinedDate: '2019-07-08',
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    engagementRate: 10.2,
    averageLikes: 78000,
    averageComments: 1890,
    averageShares: 678,
    reachRate: 17.5,
    overallScore: 93,
    engagementScore: 94,
    growthScore: 91,
    consistencyScore: 94,
    followerGrowth30d: 23400,
    followerGrowth7d: 6200,
    status: 'active',
    tier: 'platinum',
  },
  {
    id: '10',
    username: '@art_carlos',
    fullName: 'Carlos Ramirez',
    platform: 'instagram',
    profileImage: 'https://i.pravatar.cc/150?img=15',
    followers: 156000,
    following: 890,
    totalPosts: 987,
    bio: 'Digital Artist | Illustrator | Commissions Open | Prints available 🎨',
    verified: false,
    category: 'Art',
    location: 'Portland, OR',
    email: 'carlos@art.com',
    joinedDate: '2021-01-22',
    lastActive: new Date(Date.now() - 21600000).toISOString(),
    engagementRate: 6.9,
    averageLikes: 9800,
    averageComments: 234,
    averageShares: 67,
    reachRate: 10.2,
    overallScore: 75,
    engagementScore: 76,
    growthScore: 72,
    consistencyScore: 78,
    followerGrowth30d: 4200,
    followerGrowth7d: 980,
    status: 'active',
    tier: 'bronze',
  },
];

// Generate Rankings from Influencers
export const MOCK_RANKINGS: Ranking[] = MOCK_INFLUENCERS
  .sort((a, b) => b.overallScore - a.overallScore)
  .map((influencer, index) => ({
    rank: index + 1,
    previousRank: index + 1 + randomBetween(-3, 3),
    influencer,
    score: influencer.overallScore,
    change: randomBetween(-5, 10),
    trend: Math.random() > 0.5 ? 'up' : Math.random() > 0.3 ? 'stable' : 'down',
  }));

// Mock QR Scans
export const MOCK_QR_SCANS: QRScan[] = [
  {
    id: 'qr1',
    influencerId: '1',
    influencerName: 'Sarah Johnson',
    eventId: 'evt1',
    eventName: 'Fashion Week NYC 2024',
    scannedAt: new Date(Date.now() - 3600000).toISOString(),
    location: 'Javits Center, NYC',
    verified: true,
    points: 50,
  },
  {
    id: 'qr2',
    influencerId: '4',
    influencerName: 'Alex Thompson',
    eventId: 'evt2',
    eventName: 'Food Festival Miami',
    scannedAt: new Date(Date.now() - 7200000).toISOString(),
    location: 'Bayfront Park, Miami',
    verified: true,
    points: 50,
  },
  {
    id: 'qr3',
    influencerId: '9',
    influencerName: 'Sophia Lee',
    eventId: 'evt3',
    eventName: 'Music Awards 2024',
    scannedAt: new Date(Date.now() - 10800000).toISOString(),
    location: 'Bridgestone Arena, Nashville',
    verified: true,
    points: 75,
  },
];

// Mock Events
export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt1',
    name: 'Fashion Week NYC 2024',
    description: 'Annual fashion week showcasing top designers and influencers',
    date: new Date(Date.now() + 86400000 * 7).toISOString(),
    location: 'Javits Center, NYC',
    type: 'conference',
    status: 'upcoming',
    attendees: 245,
    qrCode: 'QR_FW_NYC_2024',
  },
  {
    id: 'evt2',
    name: 'Food Festival Miami',
    description: 'Culinary celebration with top food influencers and chefs',
    date: new Date(Date.now() + 86400000 * 14).toISOString(),
    location: 'Bayfront Park, Miami',
    type: 'conference',
    status: 'upcoming',
    attendees: 189,
    qrCode: 'QR_FF_MIA_2024',
  },
  {
    id: 'evt3',
    name: 'Music Awards 2024',
    description: 'Annual music awards ceremony',
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    location: 'Bridgestone Arena, Nashville',
    type: 'launch',
    status: 'completed',
    attendees: 567,
    qrCode: 'QR_MA_NSH_2024',
  },
];

// Mock Activities
export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act1',
    type: 'rank_change',
    influencerId: '4',
    influencerName: 'Alex Thompson',
    description: 'Moved up 2 positions to #1',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'act2',
    type: 'qr_scan',
    influencerId: '1',
    influencerName: 'Sarah Johnson',
    description: 'Checked in at Fashion Week NYC 2024',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'act3',
    type: 'milestone',
    influencerId: '2',
    influencerName: 'Michael Chen',
    description: 'Reached 900K followers',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'act4',
    type: 'new_influencer',
    influencerId: '10',
    influencerName: 'Carlos Ramirez',
    description: 'New influencer added to tracking',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
  },
];

// Mock Analytics
export const MOCK_ANALYTICS: Analytics = {
  totalInfluencers: MOCK_INFLUENCERS.length,
  activeInfluencers: MOCK_INFLUENCERS.filter(i => i.status === 'active').length,
  totalFollowers: MOCK_INFLUENCERS.reduce((sum, i) => sum + i.followers, 0),
  averageEngagement: MOCK_INFLUENCERS.reduce((sum, i) => sum + i.engagementRate, 0) / MOCK_INFLUENCERS.length,
  topPerformers: MOCK_INFLUENCERS.slice(0, 5),
  recentActivity: MOCK_ACTIVITIES,
  growthTrend: [
    { date: '2024-11-01', followers: 4500000, engagement: 8.2, posts: 234 },
    { date: '2024-11-05', followers: 4650000, engagement: 8.5, posts: 289 },
    { date: '2024-11-10', followers: 4820000, engagement: 8.7, posts: 312 },
    { date: '2024-11-15', followers: 5100000, engagement: 9.1, posts: 345 },
  ],
};
